### ISSUE TITLE
Setting the artifact name

### ISSUE THREAD

**Issue by evanchooly** [bmuschko/gradle-nexus-plugin#15]
I need to be able to set the artifact name to something other than the directory the project/module lives in.  I need the artifact names to match what maven has been producing and I'd rather not rename my project's directories to something dumb just to accommodate.  e.g. in morphia, the subproject "guice-plug" should generate an artifact named "morphia-guice-plug"

**Comment by Burdu** [comment]
> One way should be to set the project name in `settings.gradle` like this: `project.name = 'morphia-guice-plug'`. Another way would be to explicitly set it in the POM configuration:
> 
> ```
> modifyPom {
>     project {
>         artifactId = 'morphia-guice-plug'
>     }
> }
> ```

Sorry for posting on such an old and closed ticket, but is this way of setting the artifactId still supposed to work? It doesn't seem to on my project.

**Comment by Burdu** [comment]
Nevermind, my question appears related to this: https://github.com/bmuschko/gradle-nexus-plugin/issues/71
