### ISSUE TITLE
Support for multiple repositories

### ISSUE THREAD

**Issue by fguerout** [bmuschko/gradle-nexus-plugin#29]
If a project has multiple generated artifacts, all artifacts can currently only be uploaded to a single nexus repository URL.

 Would that be possible to add support for multiple repositories, so that we can upload one artifact (eg. .jar file) to a configured URL and another artifact (eg. .zip file) to another URL ?

**Comment by bmuschko** [comment]
This plugin reached EOL and will add no more new features.
