### ISSUE TITLE
Ability to promote staging repository

### ISSUE THREAD

**Issue by szpak** [bmuschko/gradle-nexus-plugin#40]
To have less manual clicking and/or to make releasing to Maven Central automatic from CI server It would be useful to have an ability (another task?) to promote (probably also drop) staging repository from the plugin.

It should be probably possible with [Nexus REST API](https://support.sonatype.com/entries/39720203-Uploading-to-a-Staging-Repository-via-REST-API).

**Comment by szpak** [comment]
What do you propose to use instead of HTTPBuilder? Running `curl` process from OS?

**Comment by bmuschko** [comment]
HttpClient or better HttpURLConnection. Thinking about it, I don't actually want the functionality in this plugin. It should be a separate, complimentary plugin.

**Comment by bmuschko** [comment]
I am going to close this issue. It should be easy to write a plugin that applies and augments the functionality of the Nexus plugin with tasks using the Nexus API. Either way I don't see the functionality in this plugin. Also, I'd expect quite a bit of maintenance & required testing code coming out of this functionality which I won't have the time for. Should you ever create such a plugin, let me know and I am going to link to it from this plugin's documentation page.

**Comment by szpak** [comment]
I decided to write that [plugin](https://github.com/Codearte/gradle-nexus-staging-plugin) and in the end it turned out that there are some corner cases to support (so probably good that you haven't decide to have that feature).
My plugin is upload mechanism agnostic (it just uses REST API), but I was thinking about better integration with gradle-nexus-plugin (when available). I wanted to reuse credentials provided for your plugin, but looking at your code it seems I could only try to find nexusPassword/nexusUsername or try to find upload task(s) and get credentials from they (if available). Do you have any other idea what could be done on that field?

**Comment by bmuschko** [comment]
I am not quite sure what other credentials you are looking for other than username/password. If you can give me more information, I might be able to give you a better answer.

**Comment by szpak** [comment]
After post my comment I realized that your plugin does not keep credentials itself, but only set authentication in a repository.

I was able to [implement](https://github.com/Codearte/gradle-nexus-staging-plugin/blob/master/src/main/groovy/io/codearte/gradle/nexus/NexusStagingPlugin.groovy#L83-L101) getting credentials with manually configured authentication section, but to use credentials set by your plugin I would need in addition to call my code in `taskGraph.whenReady {}` closure. That needs #47 and in addition one question to you: do `taskGraph.whenReady {}` closures are executed in the order they were created or it is not guaranteed?

**Comment by bmuschko** [comment]
Order is not guarenteed by Gradle.

**Comment by szpak** [comment]
> Order is not guarenteed by Gradle.

So to be sure to be after taskReady do I have to it in doFirst in my task or there is a better way?

**Comment by bmuschko** [comment]
I think I'd have to see the code but `doFirst` is a valid option. The only downside is going to be that you can't use the fields as input properties for your tasks.
