### ISSUE TITLE
Does this plugin support multi-project build?

### ISSUE THREAD

**Issue by shintasmith** [bmuschko/gradle-nexus-plugin#43]
I am having issues with using this plugin on a multi-project build. The error I got was:
```
* What went wrong:
A problem occurred configuring root project 'parent-proj'.
> Task with name 'install' not found in root project 'parent-proj'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by bmuschko** [comment]
Should work. 

* Where and how are you applying the plugin?
* How do you execute the Gradle command and from what directory?

**Comment by bmuschko** [comment]
Without more information I won't be able to help. Please reopen if you can provide additional input.
