### ISSUE TITLE
Ability to define additional tasks which should trigger setting authentication for repository

### ISSUE THREAD

**Issue by szpak** [bmuschko/gradle-nexus-plugin#47]
When using with [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/) it would be useful to trigger setting authentication for a repository even when `uploadArchives` task is not in a task graph. Then gradle-nexus-staging-plugin could reuse credentials defined with gradle-nexus-plugin executing its own `closeRepository` and `promoteRepository` tasks.

Those task would be defined in the nexus configuration closure.

@bmuschko if you like the idea I could provide a pull request.

**Comment by bmuschko** [comment]
I don't quite understand what we are trying achieve. Can you elaborate?

**Comment by bmuschko** [comment]
I guess that provided by your own plugin now.
