### ISSUE TITLE
Optional flag not generated in pom

### ISSUE THREAD

**Issue by ben-manes** [bmuschko/gradle-nexus-plugin#56]
This plugin does not retain the **optional** flag on a dependency, as set by the [gradle-extra-configurations-plugin](https://github.com/nebula-plugins/gradle-extra-configurations-plugin). When using the example with this plugin the dependency is not marked as optional, but if the plugin is removed the metadata is generated correctly.

```gradle
apply plugin: 'com.bmuschko.nexus'
apply plugin: 'optional-base'
  
dependencies {
  compile 'org.apache.commons:commons-lang3:3.3.2', optional
  compile group: 'log4j', name: 'log4j', version: '1.2.17', optional
}
```

```xml
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-lang3</artifactId>
  <version>3.3.2</version>
  <scope>compile</scope>
</dependency>
<dependency>
  <groupId>log4j</groupId>
  <artifactId>log4j</artifactId>
  <version>1.2.17</version>
  <scope>compile</scope>
</dependency>
```

**Comment by bmuschko** [comment]
It's probably some evaluation order problem. Would you be interested in looking the problem and identifying a fix?

**Comment by ben-manes** [comment]
Unfortunately I'm swamped and probably won't investigate soon. I haven't had the time to work through the backlog of tasks for my own gradle plugin and I have other project commitments. I think I decided to use `provided` scope which was a satisfactory workaround.

**Comment by bmuschko** [comment]
OK, I guess I am going to close the issue then. Feel free to reopen if the you ever want to revisit.
