### ISSUE TITLE
Multiple GPG key passphase questions in multi-project builds

### ISSUE THREAD

**Issue by szpak** [bmuschko/gradle-nexus-plugin#57]
`gradle-nexus-plugin` (and transitively `sign` plugin) are applied to all releasable sub-modules, but it would be nice to get a GPG key passphase question only once.

**Comment by bmuschko** [comment]
The credentials should be provided by a different plugin than the Nexus plugin. At the moment this logic is mixed in. I'd like to remove the logic from the plugin overall so consumers can write their code for handling these situations. This answer doesn't help you right now. At the moment I simply don't have any time to work on the plugin.

**Comment by bmuschko** [comment]
I am going to close the issue. The plugin won't support further functionality on the credentials-side.
