### ISSUE TITLE
uploadArchives task fails with Gradle 2.3+ when distZip and distTar are not enabled

### ISSUE THREAD

**Issue by lukosan** [bmuschko/gradle-nexus-plugin#58]
Here's the excerpt from my ```build.gradle```

```groovy
subprojects {
	apply plugin: 'java'
	apply plugin: 'eclipse'
	apply plugin: 'spring-boot'
	apply plugin: 'com.bmuschko.nexus'
	
	// these swallow disk space like a baleen whale swallows krill
	distTar.enabled = false
	distZip.enabled = false
	
	project.group = 'my-project-group'
	
	// disable fatjars too
	bootRepackage.enabled = false
	
	sourceCompatibility = 1.8
	targetCompatibility = 1.8

	extraArchive {
		sources = true
		tests = false
		javadoc = false
	}
	
	ext.nexusUsername = 'my-username'
	ext.nexusPassword = 'my-password'
	
	nexus {
		sign = false
		repositoryUrl = nexusUrl + '/nexus/content/repositories/releases'
		snapshotRepositoryUrl = nexusUrl + '/nexus/content/repositories/snapshots'
	}
	
	jar {
		baseName = project.name
		version =  currentVersion
	}
	
	springBoot {
		mainClass = 'my.main.class.Application'
	}
	
	modifyPom {
		project {
			name project.name
			description project.description
			url 'https://www.myurl.com/'
			inceptionYear '2015'
	
			groupId 'my-project-group'
			artifactId project.name
			version coverCoreVersion
			
			scm {
				url 'https://bitbucket.org/blah-blah-blah'
				connection 'scm:git@bitbucket.org:blah-blah-blah.git'
				developerConnection 'scm:git@bitbucket.org:blah-blah-blah.git'
			}
			
			// NB this is a collection of org.apache.maven.model.Dependency objects
			dependencies.findAll { dep -> dep.version == 'unspecified' }.each { d ->
				d.groupId = 'my-project-group'
				d.version = currentVersion
			}
		}
	}
}
```
And the error is:
```
Execution failed for task ':my-subproject:uploadArchives'.
> Could not publish configuration 'archives'
   > Cannot publish artifact 'my-subproject.zip (my-project-group:my-subproject:unspecified)' (/*redacted*/build/distributions/my-subproject.zip) as it does not exist.
```

It works okay in 2.2 but not in 2.3, 2.4, 2.5, 2.6 and 2.7.

**Comment by bmuschko** [comment]
Looks like a side-effect of the Spring Boot plugin. Instead of disabling the tasks, I'd remove them from the list of outgoing artifacts. See [user guide](https://docs.gradle.org/current/userguide/artifact_management.html) for more info.

**Comment by bmuschko** [comment]
I haven't heard back from you. Closing the issue. Please reopen if you need further assistance.

**Comment by milosonator** [comment]
I'm having essentially the same error as OP (`2.1.5.RELEASE`).
Using the more modern `bootDistTar` and `bootDistZip`. I attempt to disable those with:
```groovy
bootDistTar {
  enabled = false
}

bootDistZip {
  enabled = false
}
```
Get the same error as OP: 
`Cannot publish artifact 'component-boot.zip' (/.../component-boot-version.zip) as it does not exist.`

Easiest workaround I have is to change the classifier. (whole reason I disable is that I have already another `zip` artifact, which prevent my maven uploads from being successful), like so:
```groovy
bootDistTar {
  classifier = 'bootTar'
}

bootDistZip {
  classifier = 'bootZip'
}
```

IMHO disabling the task should exclude the artifact, or the user guide should be more explicit on how to exclude those, as my attempts at excluding the artifacts were not successful.

**Comment by bmuschko** [comment]
Be aware that this plugin uses the old publishing API which will likely become obsolete in Gradle 6.0. Gradle 6.0 will switch to the "new" publishing API. Therefore, I am not planning to put in any additional work. You may want to find a future-proof alternative.
