### ISSUE TITLE
How to set classifier for archives

### ISSUE THREAD

**Issue by apatrida** [bmuschko/gradle-nexus-plugin#59]
It isn't clear if this can be set at all.

**Comment by bmuschko** [comment]
Which archives are you referring to? Are you talking about the ones created by the plugin e.g. `javadocJar`?

**Comment by bmuschko** [comment]
I haven't heard back from you. Closing the issue. Please reopen if you need further assistance.

**Comment by apatrida** [comment]
Additional libraries such as one compiled with source sets for `jdk6`, another for `jdk7`, another for `jdk8` where the classifier part of the maven identifier is set for each to represent which JDK it was compiled against.  By classifier I literally mean `classifier` as defined by Maven.

**Comment by bmuschko** [comment]
You do this the same way as I do it in the plugin: https://github.com/bmuschko/gradle-nexus-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/nexus/ExtraArchivePlugin.groovy#L58

This is really just basic Gradle functionality and is not functionality this plugin provides.
