### ISSUE TITLE
how to add additional archives to publish 

### ISSUE THREAD

**Issue by apatrida** [bmuschko/gradle-nexus-plugin#60]
I cannot find a way for the plugin to send arbitrary other archives to maven repo.

**Comment by bmuschko** [comment]
Assuming you are sticking with the default configuration `archives` then this should work as usual in a Gradle project. See [user guide](https://docs.gradle.org/current/userguide/artifact_management.html) for more info.

    task myJar(type: Jar)

    artifacts {
        archives myJar
    }

**Comment by bmuschko** [comment]
I haven't heard back from you. Closing the issue. Please reopen if you need further assistance.

**Comment by apatrida** [comment]
Thanks, will try it.
