### ISSUE TITLE
"Must specify a repository for deployment" error

### ISSUE THREAD

**Issue by viveleroi** [bmuschko/gradle-nexus-plugin#61]
`upload` tasks always fail with the following error:

```
Execution failed for task ':uploadArchives'.
> Could not publish configuration 'archives'
   > Must specify a repository for deployment
```

This config has worked in the past so I'm wondering if something's changed on the gradle/maven plugin side.

When I remove all nexus plugin code, the upload works.

```
// Gradle repositories and dependencies
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-nexus-plugin:2.3.1'
    }
}

// Apply plugin
apply plugin: 'java'
apply plugin: 'maven'
apply plugin: 'com.bmuschko.nexus'

// ...

uploadArchives.repositories.mavenDeployer {
    repository(url: "http://example.com/nexus/content/repositories/releases/")
    pom.version = "2.0-SNAPSHOT"
    pom.artifactId = "example"
    pom.groupId = "com.helion3"
}

extraArchive {
    sources = false
    tests = false
    javadoc = false
}

nexus {
    sign = false
    repositoryUrl = 'http://example.com/nexus/content/repositories/releases/'
    snapshotRepositoryUrl = 'http://example.com/nexus/content/repositories/snapshots/'
}
```

---
## Gradle 2.10

Build time:   2015-12-21 21:15:04 UTC
Build number: none
Revision:     276bdcded730f53aa8c11b479986aafa58e124a6

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_66 (Oracle Corporation 25.66-b17)
OS:           Mac OS X 10.11.2 x86_64

**Comment by XieXianbin** [comment]
I also meet it

**Comment by ohmerhe** [comment]
Is this problem fixed ?

**Comment by bmuschko** [comment]
Why do you use `uploadArchives.repositories.mavenDeployer`? It's not necessary. This happens under the cover by the plugin. To change the POM please use `modifyPom` as [described in the documentation](https://github.com/bmuschko/gradle-nexus-plugin#example).

**Comment by bmuschko** [comment]
I am going to close this issue as the reporter never came back to provide additional information.
