### ISSUE TITLE
Encrypt credentials in properties file

### ISSUE THREAD

**Issue by scurry** [bmuschko/gradle-nexus-plugin#63]
Many organizations can not have passwords in the clear within a file.  It is generally not a good security practice.   The idea here is that the gradle.properties file would have the password encrypted and it would be descrypted at runtime before being used to authenticate to nexus. 

Here are some _possible_ help to implement this:  
- [Gradle Creds](https://github.com/etiennestuder/gradle-credentials-plugin)
- [Gradle Maven Settings](https://github.com/mark-vieira/gradle-maven-settings-plugin)

But I will leave the implementation choice to you :)  

At the vary least, provide a "hook" so that the password could be provided by one of these solutions and let the user do the integration.

**Comment by bmuschko** [comment]
It's not the purpose of this plugin to capture user input or read/encrypt credentials. That should be the responsibility of Gradle core or another plugin. You might want to use https://github.com/etiennestuder/gradle-credentials-plugin instead.
