### ISSUE TITLE
Make authorization error more user-friendly

### ISSUE THREAD

**Issue by johnjohndoe** [bmuschko/gradle-nexus-plugin#64]
If I am trying to upload artifacts to a repository which requires sign-in credentials without having specified them in `~/.gradle/gradle.properties` the following error is shown:

```
Execution failed for task ':foobar:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts: Could not transfer artifact 
     com.example.library.foobar:foobar:aar:1.0.0-20160817.125338-10 from/to remote 
     (http://example.com/repository/example-snapshots/): Failed to transfer file: 
     http://example.com/repository/example-snapshots/com/example/library/foobar/foobar/
     1.0.0-SNAPSHOT/foobar-1.0.0-20160817.125338-10.aar. 
     Return code is: 401, ReasonPhrase: Unauthorized.
```

How about explicitly telling the user that the plugin is looking for the credentials in that location and that they could not be found?

> Return code is: 401, ReasonPhrase: Unauthorized.
> Cannot find sign-in credentials to authorize at the target repository. Please provide 'nexusUsername' and 'nexusPassword' in `~/.gradle/gradle.properties`.

**Comment by bmuschko** [comment]
This is coming from Gradle core (or to be more specific the Ant task provided by the Maven project) and would need to be fixed there. I would like to completely get away from having any credentials-related code in this plugin.

**Comment by johnjohndoe** [comment]
Can you please point me to the Ant task? I would be happy to report it there to address this UX issue.

**Comment by bmuschko** [comment]
I believe it's coming from the Aether library if I am not mistaken. See [MavenDeployAction](https://github.com/gradle/gradle/blob/master/subprojects/maven/src/main/java/org/gradle/api/publication/maven/internal/action/MavenDeployAction.java) in Gradle core for more information and further digging.
