### ISSUE TITLE
uploadArchives logging needed

### ISSUE THREAD

**Issue by saingrady** [bmuschko/gradle-nexus-plugin#66]
Hi team, 

It is possilbe to have logging when we uploadArchives ? it should something similar to ivy:publish, so we will know where it upload to.

For example: 

[ivy:publish] 	published project-name to https://nexus.domain.com/nexus/content/repositories/releases/com/company/..../project-name-1.0.0.108.zip

Kind Regards,
Rady

**Comment by bmuschko** [comment]
I am sure you can hook into the task and read additional information. Have a look at [`MavenResolver.beforeDeployment`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/maven/MavenResolver.html#beforeDeployment(org.gradle.api.Action)). If you get stuck please open a question on the Gradle forum. The `uploadArchives` task is not specific to this plugin.
