### ISSUE TITLE
How can I manually say upload to snapshot or stable repository ?

### ISSUE THREAD

**Issue by sebastienvermeille** [bmuschko/gradle-nexus-plugin#68]
Hi @bmuschko ,
small question:

I am building snapshots releases but also preview and I would like both of them goes to: **snapshot-repo**

And when I build : "final" releases or rc releases they go to "stable-repo"

Is there a way to define which repository should be used to upload inside the build task ? 

Thank you in advance for your help

**Comment by bmuschko** [comment]
What's the difference between snapshot releases and preview releases? They are effectively the same thing by definition.

I'd need to see some code that shows how this works or doesn't work right now.

**Comment by sebastienvermeille** [comment]
We use snapshots for private branche release and preview for dévelop
branch.

And well then we have rc releases and final.

I suggest to add a regex parameter for stable releases:
(stable|final|rc[0-9])

And the rest will go as instable ?
Le lun. 23 oct. 2017 à 17:55, Benjamin Muschko <notifications@github.com> a
écrit :

**Comment by sebastienvermeille** [comment]
If you guide me a little I would be happy to publish a PR

**Comment by bmuschko** [comment]
I guess the approach here would be to set the repositories based on your project version. This should be doable without changing the plugin code. Something along the lines of the following pseudo-code:

```
afterEvaluate {
     if (project.version.endsWith('SNAPSHOT') || project.version.endsWith('preview')) {
         nexus.repositoryUrl = null
         nexus.snapshotRepositoryUrl = '<snapshot-repo>'
     }
}
```

**Comment by sebastienvermeille** [comment]
Ah great ! I will give a try :)

Le mar. 31 oct. 2017 à 14:29, Benjamin Muschko <notifications@github.com> a
écrit :

**Comment by bmuschko** [comment]
Closing as there was no more traffic on this issue.
