### ISSUE TITLE
How force project version on Nexus

### ISSUE THREAD

**Issue by pascencio** [bmuschko/gradle-nexus-plugin#69]
Hi

I wrote my gradle configuration follow the example on the README page, but the version in Nexus is like current date (In my settings I used 0.0.1-SNAPSHOT). How can I change this behavior?
This is an extract of my build.gradle file:
 
```groovy
version = '1.0-SNAPSHOT'
group = '...'

jar {
    baseName = '...'
    version = '0.0.1-SNAPSHOT'
}

nexus {
    sign = false
    repositoryUrl = '...'
    snapshotRepositoryUrl = '...'
}
```

Thanks in advance!

**Comment by bmuschko** [comment]
That's normal SNAPSHOT behavior in a binary repository. Nexus will need to keep track of all published artifacts by timestamp so it can pick the latest if requested. I believe you can change that setting in the Nexus repository itself but I'd need to look at the options.

BTW: Setting the `version` property and changing the version for the `jar` task makes little sense. Why would you want to use two different versions or better "why do you want to overwrite it if it's already set"?

**Comment by pascencio** [comment]
@bmuschko, thanks for your answer. Now I understand why get that versión. So the correct configuration for version in nexus is version = "my-version", outside of jar closure.

Thanks again!
