### ISSUE TITLE
BOM support

### ISSUE THREAD

**Issue by jameskleeh** [bmuschko/gradle-nexus-plugin#70]
Can I use this plugin to upload a bom to sonatype?

Currently we are using `org.apache.maven.plugins:maven-gpg-plugin:1.3:sign-and-deploy-file`. See https://github.com/grails/grails-core/blob/3.3.x/grails-bom/build.gradle#L13

Thanks!

**Comment by bmuschko** [comment]
This plugin still uses the "old" Maven plugin. With Gradle 4.8 the "old" mechanism has been [deprecated more or less](https://docs.gradle.org/4.8/release-notes.html).

>The maven-publish and ivy-publish plugins are now considered stable and use of the maven plugin is discouraged as it will eventually be deprecated — please migrate.

In turn this plugin will likely become outdated soon or somebody else sends a pull request to use the Maven publish plugin instead. Regarding BOM support you should be able to upload other files with the Maven publish plugin without having to write your own tasks (as you do). I'd suggest you ask the question on the Gradle forum for further advice on how to do it.

With this plugin you cannot upload a BOM right now.

**Comment by bmuschko** [comment]
This plugin reached EOL and will add no more new features.
