### ISSUE TITLE
Gradle Kotli-Dsl example

### ISSUE THREAD

**Issue by herveDarritchon** [bmuschko/gradle-nexus-plugin#74]
hi,

in my project, I use kotlin-dsl for gradle and I want to release in maven central.
Your plugin looks great but I can't manage to translate the groovy style in the kotlin-dsl style.

It could be great if in the doc, there is also a kotlin-dsl style example.

Could someone do it ?

Thanks.

Hervé

**Comment by bmuschko** [comment]
I am not actively developing the plugin anymore. If you would like to get assistance for this plugin then it has to come from the community. Just wanted to mention that this plugin uses the "old" publishing API which will go away in Gradle 6.0 I believe so you might want to look for better alternatives.

**Comment by herveDarritchon** [comment]
@bmuschko Thanks for replying  ... indeed, Gradle 6.0 is not far away so I will try to find an other alternative. Your plugin is in everywhere tutorial to release to maven central ! Thanks for the great job you have done ... It's a shame I arrive to late ;)
Best.

**Comment by bmuschko** [comment]
I am going to close this issue. Cheers!
