### ISSUE TITLE
MavenPlugin is deprecated and scheduled to be removed in Gradle 7.0

### ISSUE THREAD

**Issue by admapere** [bmuschko/gradle-nexus-plugin#76]
The MavenPlugin.java in Gradle is [deprecated](https://github.com/gradle/gradle/blob/master/subprojects/maven/src/main/java/org/gradle/api/plugins/MavenPlugin.java) and scheduled to be removed. 

I was able to determine that the plugin is imported in the following files in this repo:
./src/integTest/groovy/com/bmuschko/gradle/nexus/singleproject/SingleProjectInstallIntegrationTest.groovy
./src/main/groovy/com/bmuschko/gradle/nexus/NexusPlugin.groovy
./src/main/groovy/com/bmuschko/gradle/nexus/NexusPluginExtension.groovy

**Comment by bmuschko** [comment]
You are correct but I am not planning to incorporate the Maven Publish Plugin. If the community would like to have the functionality, then someone will have to provide a pull request.

**Comment by bmuschko** [comment]
As explained above. This plugin reached EOL.
