### ISSUE TITLE
Publish to Gradle Plugins repo

### ISSUE THREAD

**Issue by jaredsburrows** [bmuschko/gradle-nexus-plugin#78]
Can you publish this to the Gradle Plugins repo?

**Comment by jaredsburrows** [comment]
Found it here - https://plugins.gradle.org/plugin/com.bmuschko.nexus.

**Comment by bmuschko** [comment]
Be aware that the plugin will likely not work anymore with Gradle 7.x. I believe the plan is to remove the original Maven plugin from Gradle core. I would actually not recommend to use this plugin anymore.

**Comment by jaredsburrows** [comment]
Alright, thanks!
